package Model;
// Generated 25-may-2018 20:04:55 by Hibernate Tools 4.3.1



/**
 * UbicacionId generated by hbm2java
 */
public class UbicacionId  implements java.io.Serializable {


     private String pasillo;
     private String estante;
     private String balda;

    public UbicacionId() {
    }

    public UbicacionId(String pasillo, String estante, String balda) {
       this.pasillo = pasillo;
       this.estante = estante;
       this.balda = balda;
    }
   
    public String getPasillo() {
        return this.pasillo;
    }
    
    public void setPasillo(String pasillo) {
        this.pasillo = pasillo;
    }
    public String getEstante() {
        return this.estante;
    }
    
    public void setEstante(String estante) {
        this.estante = estante;
    }
    public String getBalda() {
        return this.balda;
    }
    
    public void setBalda(String balda) {
        this.balda = balda;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UbicacionId) ) return false;
		 UbicacionId castOther = ( UbicacionId ) other; 
         
		 return ( (this.getPasillo()==castOther.getPasillo()) || ( this.getPasillo()!=null && castOther.getPasillo()!=null && this.getPasillo().equals(castOther.getPasillo()) ) )
 && ( (this.getEstante()==castOther.getEstante()) || ( this.getEstante()!=null && castOther.getEstante()!=null && this.getEstante().equals(castOther.getEstante()) ) )
 && ( (this.getBalda()==castOther.getBalda()) || ( this.getBalda()!=null && castOther.getBalda()!=null && this.getBalda().equals(castOther.getBalda()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPasillo() == null ? 0 : this.getPasillo().hashCode() );
         result = 37 * result + ( getEstante() == null ? 0 : this.getEstante().hashCode() );
         result = 37 * result + ( getBalda() == null ? 0 : this.getBalda().hashCode() );
         return result;
   }   


}


