package Model;
// Generated 25-may-2018 20:04:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ubicacion generated by hbm2java
 */
public class Ubicacion  implements java.io.Serializable {


     private UbicacionId id;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Ubicacion() {
    }

	
    public Ubicacion(UbicacionId id) {
        this.id = id;
    }
    public Ubicacion(UbicacionId id, Set<Producto> productos) {
       this.id = id;
       this.productos = productos;
    }
   
    public UbicacionId getId() {
        return this.id;
    }
    
    public void setId(UbicacionId id) {
        this.id = id;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


