package Model;
// Generated 25-may-2018 20:04:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String apellido;
     private String tlf;
     private String email;
     private String password;
     private Set<Lista> listas = new HashSet<Lista>(0);

    public Usuario() {
    }

	
    public Usuario(String dni, String nombre, String email, String password) {
        this.dni = dni;
        this.nombre = nombre;
        this.email = email;
        this.password = password;
    }
    public Usuario(String dni, String nombre, String apellido, String tlf, String email, String password, Set<Lista> listas) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellido = apellido;
       this.tlf = tlf;
       this.email = email;
       this.password = password;
       this.listas = listas;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTlf() {
        return this.tlf;
    }
    
    public void setTlf(String tlf) {
        this.tlf = tlf;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Lista> getListas() {
        return this.listas;
    }
    
    public void setListas(Set<Lista> listas) {
        this.listas = listas;
    }




}


