package Entities;
// Generated 25-may-2018 20:04:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lista generated by hbm2java
 */
public class Lista  implements java.io.Serializable {


     private Integer idLista;
     private Usuario usuario;
     private String nombre;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Lista() {
    }

	
    public Lista(Integer idLista, Usuario usuario, String nombre) {
        this.idLista = idLista;
        this.usuario = usuario;
        this.nombre = nombre;
    }
    public Lista(Integer idLista, Usuario usuario, String nombre, Set<Producto> productos) {
       this.idLista = idLista;
       this.usuario = usuario;
       this.nombre = nombre;
       this.productos = productos;
    }
   
    public Integer getIdLista() {
        return this.idLista;
    }
    
    public void setIdLista(Integer idLista) {
        this.idLista = idLista;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


